In [1]:
# 作業目標
# 讀取存取陣列資料
# 作業重點
# 多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

# 題目:

# 將下兩列array存成npz檔
# array1 = np.array(range(30))
# array2 = np.array([2,3,5])
# 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [4]:
import numpy as np

In [28]:
# 1.將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

with open("two_array.npz","wb") as f:
    np.savez(f,array1=array1,array2=array2)

In [29]:
# 2.讀取剛剛的npz檔，加入下列array一起存成新的npz檔

npzfile = np.load("two_array.npz")
npzfile.files

['array1', 'array2']

In [30]:
print(npzfile["array1"])
print(npzfile["array2"])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [31]:
array3 = np.array(range(10))
with open("three_array.npz","wb") as f:
    np.savez(f,array1=array1 , array2=array2 ,array3=array3)

In [32]:
npzfile = np.load("three_array.npz")
npzfile.files

['array1', 'array2', 'array3']

In [33]:
print(npzfile["array1"])
print(npzfile["array2"])
print(npzfile["array3"])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
